### ISSUE TITLE
v4.1.3 breaks entity setup on HA Core 2026.9+ — async_get_device_by_identifier() missing config_entry_id argument

### ISSUE THREAD

**Issue by mrath1201** [johnnyh1975/ha_roomba_plus#155]
**Environment:**

Roomba+ version: v4.1.3 (regression; v4.1.2 works fine on the same HA version)
Home Assistant Core: 2026.9.1
Install type: Home Assistant OS
Affected devices: 2 robots (Roomba, Braava)

**Description:**
After updating to v4.1.3 and restarting on HA Core 2026.9.1, every entity across both robot config entries fails to load (100+ entities: sensor, binary_sensor, button, select, switch, image, calendar, device_tracker, vacuum). The robots remain fully reachable via the iRobot app and local WiFi — only the Home Assistant side is affected.

**Traceback (identical for every entity):**

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 725, in _async_add_entities
    await self._async_add_entity(
        entity, False, entity_registry, config_subentry_id
    )
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1127, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1444, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/roomba_plus/entity.py", line 314, in async_added_to_hass
    await self._async_update_device_name()
  File "/config/custom_components/roomba_plus/entity.py", line 378, in _async_update_device_name
    device = _by_identifier((DOMAIN, self.robot_unique_id))
TypeError: DeviceRegistry.async_get_device_by_identifier() missing 1 required positional argument: 'config_entry_id'
```

**Root cause (suspected):** homeassistant.helpers.device_registry.DeviceRegistry.async_get_device_by_identifier() now requires a config_entry_id argument on HA Core 2026.9+. entity.py's _async_update_device_name() (line 378) still calls it with only the identifiers tuple.

**Workaround:** Downgrading to v4.1.2 via HACS resolves it completely — confirmed no recurrence of the error after a full restart.

**Comment by johnnyh1975** [comment]
@mrath1201 
Your suspected root cause is the actual root cause, exactly as you wrote it. Sorry for the broken evening.

**4.1.4 is out and fixes it.** Go straight there from 4.1.2 — no need to pass through 4.1.3.

## What happened

4.1.3 added a change meant to silence a Home Assistant deprecation warning, preferring `async_get_device_by_identifier()` where it exists. **I wrote that call from the method's name rather than its signature.** It does not exist in HA 2025.5, the minimum this integration supports, so nothing in my test environment could call it and nothing could tell me it takes more arguments.

Every entity goes through `_async_update_device_name` during setup, so one `TypeError` there means nothing loads. Anyone on HA 2026.x hit it; anyone on an older release saw nothing at all, which is how it got past me.

## The fix is not a revert

After the reports I read Home Assistant's migration note instead of guessing again. The real signature is `async_get_device_by_identifier((DOMAIN, serial), entry.entry_id)` — both positional, identifier first.

But the same note gives better advice than either version: inside an entity, prefer `self.device_entry` over a registry lookup. It has been on `Entity` for years and works on every supported release, so the question of which lookup to call goes away. A guard now fails the build if anything reaches for the unverifiable method again.

## Two things in your report were unusually useful

You pinned it to **v4.1.2 works, v4.1.3 does not, same HA version** — that removes Home Assistant, your robots and your config from the picture in one line.

And you noted the robots stayed reachable via the app and local WiFi, which rules out the whole connectivity layer before anyone starts looking at it.

The traceback with the full frame chain rather than just the last line is what showed every entity taking the same path.

---

4.1.4 also fixes something unrelated you may have seen: `clean_room` logged an error about response data after the robot had already cleaned. Harmless, but confusing, and now gone.
